version: '3.8'

services:

    mysql:
        image: "mysql/mysql-server:8.0.21"
        container_name: mysql
        command: [ "mysqld",
                    "--character-set-server=utf8mb4",
                    "--collation-server=utf8mb4_unicode_ci",
                    "--bind-address=0.0.0.0",
                    "--require_secure_transport=ON",
                    "--ssl-ca=/etc/certs/hashicorp-ca.pem",
                    "--ssl-cert=/etc/certs/mysql-server.pem",
                    "--ssl-key=/etc/certs/mysql-server-key.pem",
                    "--default_authentication_plugin=mysql_native_password" ]
        ports:
            - "3306:3306"
        volumes:
#             - type: bind
#               source: ./database
#               target: /var/lib/mysql
            - type: bind
              source: ./certs
              target: /etc/certs/
        restart: always
        environment:
           MYSQL_ROOT_PASSWORD: "yoursql"
           MYSQL_ROOT_HOST: "%"
