apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-app
---
apiVersion: v1
kind: Secret
metadata:
  name: internal-app-token
  annotations:
    kubernetes.io/service-account.name: "internal-app"
type: kubernetes.io/service-account-token
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  extra: YmFyCg==
