{
 "title": "Agent telemetry",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Agent Auth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Agent Auth Success counter",
   "type": "timeseries",
   "description": "Number of authentication successes",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1 },
   "targets": [
    { "expr": "vault_agent_auth_success" }
   ]
  },
  {
   "title": "Agent Auth Failure counter",
   "type": "timeseries",
   "description": "Number of authentication failures",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 1 },
   "targets": [
    { "expr": "vault_agent_auth_failure" }
   ]
  },
  { "title": "Agent Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Agent Cache Hit counter",
   "type": "timeseries",
   "description": "Number of cache hits",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "targets": [
    { "expr": "vault_agent_cache_hit" }
   ]
  },
  {
   "title": "Agent Cache Miss counter",
   "type": "timeseries",
   "description": "Number of cache misses",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 9 },
   "targets": [
    { "expr": "vault_agent_cache_miss" }
   ]
  },
  { "title": "Agent Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Agent Proxy Success counter",
   "type": "timeseries",
   "description": "Number of requests successfully proxied",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
   "targets": [
    { "expr": "vault_agent_proxy_success" }
   ]
  },
  {
   "title": "Agent Proxy Client Error counter",
   "type": "timeseries",
   "description": "Number of requests for which Vault returned an error",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 18 },
   "targets": [
    { "expr": "vault_agent_proxy_client_error" }
   ]
  },
  {
   "title": "Agent Proxy Error counter",
   "type": "timeseries",
   "description": "Number of requests the agent failed to proxy",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 18 },
   "targets": [
    { "expr": "vault_agent_proxy_error" }
   ]
  },
  { "title": "CPU/Mem Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Heap Objects Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_runtime_heap_objects{} / vault_runtime_malloc_count{})"
    }
   ]
  },
  {
   "title": "Number of Goroutines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(vault_runtime_num_goroutines{})"
    }
   ]
  },
  {
   "title": "Allocated MB",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(vault_runtime_alloc_bytes{})",
     "legendFormat": "$node"
    }
   ]
  }
 ]
}